# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20160807_1040'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notetag',
            table='note_tag',
        ),
    ]
