# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='网址')),
                ('oj', models.CharField(max_length=30, verbose_name='所属OJ')),
                ('oj_id', models.CharField(max_length=30, verbose_name='OJ题号')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('description', models.TextField(max_length=30000, verbose_name='问题描述')),
                ('hint', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('AC_time', models.DateTimeField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'problem',
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=256, verbose_name='网址')),
                ('name', models.CharField(max_length=30, verbose_name='标签')),
                ('intro', models.TextField(default='', verbose_name='简介')),
            ],
            options={
                'db_table': 'problem_tag',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='problem.ProblemTag'),
        ),
    ]
