# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oj', models.CharField(max_length=30, verbose_name='所属OJ')),
                ('oj_id', models.CharField(max_length=30, verbose_name='OJ题号')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('description', models.TextField(max_length=30000, verbose_name='问题描述')),
                ('hint', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('var', models.IntegerField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.MyUser')),
            ],
            options={
                'db_table': 'problem',
                'ordering': ['oj', 'oj_id'],
            },
        ),
        migrations.CreateModel(
            name='ProblemTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='标签')),
                ('abbreviation', models.CharField(default='', max_length=10, unique=True, verbose_name='简称')),
                ('intro', models.TextField(default='', verbose_name='简介')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'problem_tag',
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(to='problem.ProblemTag'),
        ),
    ]
