# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
