# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 02:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20160728_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 28, 2, 24, 33, 438083, tzinfo=utc), verbose_name='发表时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
