# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20160728_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['update_time']},
        ),
        migrations.AlterModelTable(
            name='note',
            table='note',
        ),
    ]
