# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 02:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0004_auto_20160803_1557'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='problemtag',
            table='tag',
        ),
    ]
