# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20160728_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('AC_time', models.DateTimeField(blank=True, null=True)),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.MyUser')),
            ],
            options={
                'db_table': 'relation',
            },
        ),
        migrations.RemoveField(
            model_name='problem',
            name='AC_time',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='problemtag',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 28, 12, 11, 12, 443675, tzinfo=utc), verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relation',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
