# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0005_auto_20160807_1030'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='problemtag',
            table='problem_tag',
        ),
    ]
