# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20160807_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_description',
            field=models.TextField(default='', max_length=10000, verbose_name='输入描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.CharField(default='', max_length=50, verbose_name='时间限制'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='output_description',
            field=models.TextField(default='', max_length=10000, verbose_name='输出描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.CharField(default='', max_length=50, verbose_name='时间限制'),
            preserve_default=False,
        ),
    ]
