# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20160728_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemtag',
            name='abbreviation',
            field=models.CharField(default='', max_length=10, verbose_name='简称'),
        ),
    ]
