# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_problemtag_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='var',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
