# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0007_auto_20160808_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='problem.ProblemTag'),
        ),
    ]
