# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_auto_20160808_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input',
            field=models.TextField(default='', max_length=10000, verbose_name='输入'),
        ),
        migrations.AddField(
            model_name='problem',
            name='output',
            field=models.TextField(default='', max_length=10000, verbose_name='输出'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_description',
            field=models.TextField(default='', max_length=10000, verbose_name='输入描述'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_description',
            field=models.TextField(default='', max_length=10000, verbose_name='输出描述'),
        ),
    ]
