# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0008_problem_var'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='context',
            new_name='content',
        ),
    ]
