# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0009_auto_20160808_1529'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set([('oj', 'oj_id')]),
        ),
    ]
